let koa = require('koa')
let logger = require('koa-logger')
let bodyparser = require('koa-bodyparser')

let {cors, static} = require('./dev')
let router = require('./routes')
let init = require('./models')

new koa()
	.use(cors())
	.use(static())
	.use(logger())
	.use(bodyparser())
	.use(router.routes())
	.use(router.allowedMethods())
	.listen(process.env.PORT)
